//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 11/8/2011 11:16:12 AM
namespace IousAzure.TesteIntegrado.ReferenciaAoServico
{
    
    /// <summary>
    /// There are no comments for ContextoBd in the schema.
    /// </summary>
    public partial class ContextoBd : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new ContextoBd object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ContextoBd(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("IousAzure.Entidades", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("IousAzure.TesteIntegrado.ReferenciaAoServico", typeName.Substring(19)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("IousAzure.TesteIntegrado.ReferenciaAoServico", global::System.StringComparison.Ordinal))
            {
                return string.Concat("IousAzure.Entidades.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Inquilinos in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Inquilino> Inquilinos
        {
            get
            {
                if ((this._Inquilinos == null))
                {
                    this._Inquilinos = base.CreateQuery<Inquilino>("Inquilinos");
                }
                return this._Inquilinos;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Inquilino> _Inquilinos;
        /// <summary>
        /// There are no comments for Usuarios in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Usuario> Usuarios
        {
            get
            {
                if ((this._Usuarios == null))
                {
                    this._Usuarios = base.CreateQuery<Usuario>("Usuarios");
                }
                return this._Usuarios;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Usuario> _Usuarios;
        /// <summary>
        /// There are no comments for Solicitacoes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Solicitacao> Solicitacoes
        {
            get
            {
                if ((this._Solicitacoes == null))
                {
                    this._Solicitacoes = base.CreateQuery<Solicitacao>("Solicitacoes");
                }
                return this._Solicitacoes;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Solicitacao> _Solicitacoes;
        /// <summary>
        /// There are no comments for SolicitacaoItens in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<SolicitacaoItem> SolicitacaoItens
        {
            get
            {
                if ((this._SolicitacaoItens == null))
                {
                    this._SolicitacaoItens = base.CreateQuery<SolicitacaoItem>("SolicitacaoItens");
                }
                return this._SolicitacaoItens;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<SolicitacaoItem> _SolicitacaoItens;
        /// <summary>
        /// There are no comments for EdmMetadatas in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<EdmMetadata> EdmMetadatas
        {
            get
            {
                if ((this._EdmMetadatas == null))
                {
                    this._EdmMetadatas = base.CreateQuery<EdmMetadata>("EdmMetadatas");
                }
                return this._EdmMetadatas;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<EdmMetadata> _EdmMetadatas;
        /// <summary>
        /// There are no comments for Inquilinos in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToInquilinos(Inquilino inquilino)
        {
            base.AddObject("Inquilinos", inquilino);
        }
        /// <summary>
        /// There are no comments for Usuarios in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToUsuarios(Usuario usuario)
        {
            base.AddObject("Usuarios", usuario);
        }
        /// <summary>
        /// There are no comments for Solicitacoes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSolicitacoes(Solicitacao solicitacao)
        {
            base.AddObject("Solicitacoes", solicitacao);
        }
        /// <summary>
        /// There are no comments for SolicitacaoItens in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSolicitacaoItens(SolicitacaoItem solicitacaoItem)
        {
            base.AddObject("SolicitacaoItens", solicitacaoItem);
        }
        /// <summary>
        /// There are no comments for EdmMetadatas in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToEdmMetadatas(EdmMetadata edmMetadata)
        {
            base.AddObject("EdmMetadatas", edmMetadata);
        }
    }
    /// <summary>
    /// There are no comments for IousAzure.Entidades.Inquilino in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Inquilinos")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Inquilino : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Inquilino object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Inquilino CreateInquilino(int ID)
        {
            Inquilino inquilino = new Inquilino();
            inquilino.Id = ID;
            return inquilino;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Nome in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Nome
        {
            get
            {
                return this._Nome;
            }
            set
            {
                this.OnNomeChanging(value);
                this._Nome = value;
                this.OnNomeChanged();
                this.OnPropertyChanged("Nome");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Nome;
        partial void OnNomeChanging(string value);
        partial void OnNomeChanged();
        /// <summary>
        /// There are no comments for Usuarios in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Usuario> Usuarios
        {
            get
            {
                return this._Usuarios;
            }
            set
            {
                this._Usuarios = value;
                this.OnPropertyChanged("Usuarios");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Usuario> _Usuarios = new global::System.Data.Services.Client.DataServiceCollection<Usuario>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Solicitacoes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Solicitacao> Solicitacoes
        {
            get
            {
                return this._Solicitacoes;
            }
            set
            {
                this._Solicitacoes = value;
                this.OnPropertyChanged("Solicitacoes");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Solicitacao> _Solicitacoes = new global::System.Data.Services.Client.DataServiceCollection<Solicitacao>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for IousAzure.Entidades.Usuario in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Usuarios")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Usuario : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Usuario object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="inquilinoId">Initial value of InquilinoId.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Usuario CreateUsuario(int ID, int inquilinoId)
        {
            Usuario usuario = new Usuario();
            usuario.Id = ID;
            usuario.InquilinoId = inquilinoId;
            return usuario;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this._Email = value;
                this.OnEmailChanged();
                this.OnPropertyChanged("Email");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property Nome in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Nome
        {
            get
            {
                return this._Nome;
            }
            set
            {
                this.OnNomeChanging(value);
                this._Nome = value;
                this.OnNomeChanged();
                this.OnPropertyChanged("Nome");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Nome;
        partial void OnNomeChanging(string value);
        partial void OnNomeChanged();
        /// <summary>
        /// There are no comments for Property SaltDaSenha in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SaltDaSenha
        {
            get
            {
                return this._SaltDaSenha;
            }
            set
            {
                this.OnSaltDaSenhaChanging(value);
                this._SaltDaSenha = value;
                this.OnSaltDaSenhaChanged();
                this.OnPropertyChanged("SaltDaSenha");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SaltDaSenha;
        partial void OnSaltDaSenhaChanging(string value);
        partial void OnSaltDaSenhaChanged();
        /// <summary>
        /// There are no comments for Property HashDaSenha in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string HashDaSenha
        {
            get
            {
                return this._HashDaSenha;
            }
            set
            {
                this.OnHashDaSenhaChanging(value);
                this._HashDaSenha = value;
                this.OnHashDaSenhaChanged();
                this.OnPropertyChanged("HashDaSenha");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _HashDaSenha;
        partial void OnHashDaSenhaChanging(string value);
        partial void OnHashDaSenhaChanged();
        /// <summary>
        /// There are no comments for Property InquilinoId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int InquilinoId
        {
            get
            {
                return this._InquilinoId;
            }
            set
            {
                this.OnInquilinoIdChanging(value);
                this._InquilinoId = value;
                this.OnInquilinoIdChanged();
                this.OnPropertyChanged("InquilinoId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _InquilinoId;
        partial void OnInquilinoIdChanging(int value);
        partial void OnInquilinoIdChanged();
        /// <summary>
        /// There are no comments for Inquilino in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Inquilino Inquilino
        {
            get
            {
                return this._Inquilino;
            }
            set
            {
                this._Inquilino = value;
                this.OnPropertyChanged("Inquilino");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Inquilino _Inquilino;
        /// <summary>
        /// There are no comments for SolicitacoesDoUsuario in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Solicitacao> SolicitacoesDoUsuario
        {
            get
            {
                return this._SolicitacoesDoUsuario;
            }
            set
            {
                this._SolicitacoesDoUsuario = value;
                this.OnPropertyChanged("SolicitacoesDoUsuario");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Solicitacao> _SolicitacoesDoUsuario = new global::System.Data.Services.Client.DataServiceCollection<Solicitacao>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for SolicitacoesAAvaliar in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Solicitacao> SolicitacoesAAvaliar
        {
            get
            {
                return this._SolicitacoesAAvaliar;
            }
            set
            {
                this._SolicitacoesAAvaliar = value;
                this.OnPropertyChanged("SolicitacoesAAvaliar");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Solicitacao> _SolicitacoesAAvaliar = new global::System.Data.Services.Client.DataServiceCollection<Solicitacao>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for IousAzure.Entidades.Solicitacao in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Solicitacoes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Solicitacao : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Solicitacao object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="inquilinoId">Initial value of InquilinoId.</param>
        /// <param name="usuarioSolicitanteId">Initial value of UsuarioSolicitanteId.</param>
        /// <param name="usuarioAvaliadorId">Initial value of UsuarioAvaliadorId.</param>
        /// <param name="data">Initial value of Data.</param>
        /// <param name="valorTotal">Initial value of ValorTotal.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Solicitacao CreateSolicitacao(int ID, int inquilinoId, int usuarioSolicitanteId, int usuarioAvaliadorId, global::System.DateTime data, decimal valorTotal)
        {
            Solicitacao solicitacao = new Solicitacao();
            solicitacao.Id = ID;
            solicitacao.InquilinoId = inquilinoId;
            solicitacao.UsuarioSolicitanteId = usuarioSolicitanteId;
            solicitacao.UsuarioAvaliadorId = usuarioAvaliadorId;
            solicitacao.Data = data;
            solicitacao.ValorTotal = valorTotal;
            return solicitacao;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property InquilinoId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int InquilinoId
        {
            get
            {
                return this._InquilinoId;
            }
            set
            {
                this.OnInquilinoIdChanging(value);
                this._InquilinoId = value;
                this.OnInquilinoIdChanged();
                this.OnPropertyChanged("InquilinoId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _InquilinoId;
        partial void OnInquilinoIdChanging(int value);
        partial void OnInquilinoIdChanged();
        /// <summary>
        /// There are no comments for Property UsuarioSolicitanteId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int UsuarioSolicitanteId
        {
            get
            {
                return this._UsuarioSolicitanteId;
            }
            set
            {
                this.OnUsuarioSolicitanteIdChanging(value);
                this._UsuarioSolicitanteId = value;
                this.OnUsuarioSolicitanteIdChanged();
                this.OnPropertyChanged("UsuarioSolicitanteId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _UsuarioSolicitanteId;
        partial void OnUsuarioSolicitanteIdChanging(int value);
        partial void OnUsuarioSolicitanteIdChanged();
        /// <summary>
        /// There are no comments for Property UsuarioAvaliadorId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int UsuarioAvaliadorId
        {
            get
            {
                return this._UsuarioAvaliadorId;
            }
            set
            {
                this.OnUsuarioAvaliadorIdChanging(value);
                this._UsuarioAvaliadorId = value;
                this.OnUsuarioAvaliadorIdChanged();
                this.OnPropertyChanged("UsuarioAvaliadorId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _UsuarioAvaliadorId;
        partial void OnUsuarioAvaliadorIdChanging(int value);
        partial void OnUsuarioAvaliadorIdChanged();
        /// <summary>
        /// There are no comments for Property Data in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Data
        {
            get
            {
                return this._Data;
            }
            set
            {
                this.OnDataChanging(value);
                this._Data = value;
                this.OnDataChanged();
                this.OnPropertyChanged("Data");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Data;
        partial void OnDataChanging(global::System.DateTime value);
        partial void OnDataChanged();
        /// <summary>
        /// There are no comments for Property Descricao in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Descricao
        {
            get
            {
                return this._Descricao;
            }
            set
            {
                this.OnDescricaoChanging(value);
                this._Descricao = value;
                this.OnDescricaoChanged();
                this.OnPropertyChanged("Descricao");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Descricao;
        partial void OnDescricaoChanging(string value);
        partial void OnDescricaoChanged();
        /// <summary>
        /// There are no comments for Property Situacao in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Situacao
        {
            get
            {
                return this._Situacao;
            }
            set
            {
                this.OnSituacaoChanging(value);
                this._Situacao = value;
                this.OnSituacaoChanged();
                this.OnPropertyChanged("Situacao");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Situacao;
        partial void OnSituacaoChanging(string value);
        partial void OnSituacaoChanged();
        /// <summary>
        /// There are no comments for Property ValorTotal in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal ValorTotal
        {
            get
            {
                return this._ValorTotal;
            }
            set
            {
                this.OnValorTotalChanging(value);
                this._ValorTotal = value;
                this.OnValorTotalChanged();
                this.OnPropertyChanged("ValorTotal");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _ValorTotal;
        partial void OnValorTotalChanging(decimal value);
        partial void OnValorTotalChanged();
        /// <summary>
        /// There are no comments for Inquilino in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Inquilino Inquilino
        {
            get
            {
                return this._Inquilino;
            }
            set
            {
                this._Inquilino = value;
                this.OnPropertyChanged("Inquilino");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Inquilino _Inquilino;
        /// <summary>
        /// There are no comments for UsuarioSolicitante in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Usuario UsuarioSolicitante
        {
            get
            {
                return this._UsuarioSolicitante;
            }
            set
            {
                this._UsuarioSolicitante = value;
                this.OnPropertyChanged("UsuarioSolicitante");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Usuario _UsuarioSolicitante;
        /// <summary>
        /// There are no comments for UsuarioAvaliador in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Usuario UsuarioAvaliador
        {
            get
            {
                return this._UsuarioAvaliador;
            }
            set
            {
                this._UsuarioAvaliador = value;
                this.OnPropertyChanged("UsuarioAvaliador");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Usuario _UsuarioAvaliador;
        /// <summary>
        /// There are no comments for Itens in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<SolicitacaoItem> Itens
        {
            get
            {
                return this._Itens;
            }
            set
            {
                this._Itens = value;
                this.OnPropertyChanged("Itens");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<SolicitacaoItem> _Itens = new global::System.Data.Services.Client.DataServiceCollection<SolicitacaoItem>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for IousAzure.Entidades.SolicitacaoItem in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("SolicitacaoItens")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class SolicitacaoItem : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new SolicitacaoItem object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="solicitacaoId">Initial value of SolicitacaoId.</param>
        /// <param name="quantidade">Initial value of Quantidade.</param>
        /// <param name="valorUnitario">Initial value of ValorUnitario.</param>
        /// <param name="valorTotal">Initial value of ValorTotal.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static SolicitacaoItem CreateSolicitacaoItem(int ID, int solicitacaoId, decimal quantidade, decimal valorUnitario, decimal valorTotal)
        {
            SolicitacaoItem solicitacaoItem = new SolicitacaoItem();
            solicitacaoItem.Id = ID;
            solicitacaoItem.SolicitacaoId = solicitacaoId;
            solicitacaoItem.Quantidade = quantidade;
            solicitacaoItem.ValorUnitario = valorUnitario;
            solicitacaoItem.ValorTotal = valorTotal;
            return solicitacaoItem;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property SolicitacaoId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SolicitacaoId
        {
            get
            {
                return this._SolicitacaoId;
            }
            set
            {
                this.OnSolicitacaoIdChanging(value);
                this._SolicitacaoId = value;
                this.OnSolicitacaoIdChanged();
                this.OnPropertyChanged("SolicitacaoId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SolicitacaoId;
        partial void OnSolicitacaoIdChanging(int value);
        partial void OnSolicitacaoIdChanged();
        /// <summary>
        /// There are no comments for Property Descricao in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Descricao
        {
            get
            {
                return this._Descricao;
            }
            set
            {
                this.OnDescricaoChanging(value);
                this._Descricao = value;
                this.OnDescricaoChanged();
                this.OnPropertyChanged("Descricao");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Descricao;
        partial void OnDescricaoChanging(string value);
        partial void OnDescricaoChanged();
        /// <summary>
        /// There are no comments for Property Quantidade in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal Quantidade
        {
            get
            {
                return this._Quantidade;
            }
            set
            {
                this.OnQuantidadeChanging(value);
                this._Quantidade = value;
                this.OnQuantidadeChanged();
                this.OnPropertyChanged("Quantidade");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _Quantidade;
        partial void OnQuantidadeChanging(decimal value);
        partial void OnQuantidadeChanged();
        /// <summary>
        /// There are no comments for Property ValorUnitario in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal ValorUnitario
        {
            get
            {
                return this._ValorUnitario;
            }
            set
            {
                this.OnValorUnitarioChanging(value);
                this._ValorUnitario = value;
                this.OnValorUnitarioChanged();
                this.OnPropertyChanged("ValorUnitario");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _ValorUnitario;
        partial void OnValorUnitarioChanging(decimal value);
        partial void OnValorUnitarioChanged();
        /// <summary>
        /// There are no comments for Property ValorTotal in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal ValorTotal
        {
            get
            {
                return this._ValorTotal;
            }
            set
            {
                this.OnValorTotalChanging(value);
                this._ValorTotal = value;
                this.OnValorTotalChanged();
                this.OnPropertyChanged("ValorTotal");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _ValorTotal;
        partial void OnValorTotalChanging(decimal value);
        partial void OnValorTotalChanged();
        /// <summary>
        /// There are no comments for Solicitacao in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Solicitacao Solicitacao
        {
            get
            {
                return this._Solicitacao;
            }
            set
            {
                this._Solicitacao = value;
                this.OnPropertyChanged("Solicitacao");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Solicitacao _Solicitacao;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for IousAzure.Entidades.EdmMetadata in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("EdmMetadatas")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class EdmMetadata : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new EdmMetadata object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static EdmMetadata CreateEdmMetadata(int ID)
        {
            EdmMetadata edmMetadata = new EdmMetadata();
            edmMetadata.Id = ID;
            return edmMetadata;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property ModelHash in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModelHash
        {
            get
            {
                return this._ModelHash;
            }
            set
            {
                this.OnModelHashChanging(value);
                this._ModelHash = value;
                this.OnModelHashChanged();
                this.OnPropertyChanged("ModelHash");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModelHash;
        partial void OnModelHashChanging(string value);
        partial void OnModelHashChanged();
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
